[build]
buildCommand = "npm install && npx prisma generate && cd scraper && npm install && npm run build"

[deploy]
startCommand = "node scraper/dist/scraper/src/index.js"

[[cron]]
schedule = "0 13 * * *"

[[cron]]
schedule = "0 4 * * *"
